📃 updated subs script to newest version with mpv socat addition

diff --git a/.local/bin/scripts/subs b/.local/bin/scripts/subs
--- a/.local/bin/scripts/subs
+++ b/.local/bin/scripts/subs
@@ -1,4 +1,12 @@
 #!/bin/sh
+#                     █████            
+#                    ▒▒███             
+#   █████  █████ ████ ▒███████   █████ 
+#  ███▒▒  ▒▒███ ▒███  ▒███▒▒███ ███▒▒  
+# ▒▒█████  ▒███ ▒███  ▒███ ▒███▒▒█████ 
+#  ▒▒▒▒███ ▒███ ▒███  ▒███ ▒███ ▒▒▒▒███
+#  ██████  ▒▒████████ ████████  ██████ 
+# ▒▒▒▒▒▒    ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒  
 #
 # Watch your youtube subscriptions without a youtube account
 # via curl, dmenu, mpv and basic unix commands.
@@ -9,15 +17,21 @@
 # For more information and examples, see:
 # http://github.com/mitchweaver/subs
 #
+# >> note: this is highly experimental / janky, it can and will break <<
+#
 # -/-/-/-/- Settings -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
 : "${SUBS_FILE:=~/files/subs.txt}"
 : "${SUBS_MENU_PROG:=dmenu}"
 : "${SUBS:=${XDG_CACHE_HOME:-~/.cache}/subs}"
 : "${SUBS_LINKS:=$SUBS/links}"
 : "${SUBS_CACHE:=$SUBS/cache}"
-: "${SUBS_SLEEP_VALUE:=0.05}" # raise this if you experience problems
+: "${SUBS_SLEEP_VALUE:=1}" # raise this if you experience problems
+: "${SUBS_DAEMON_INTERVAL:=600}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 SEP=^^^^^ # shouldn't need to change this
+# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
+export LC_ALL=C    # this speeds things up a bit but can cause
+                   # issues for titles in foreign languages
 # -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
 
 die() {
@@ -26,7 +40,7 @@ die() {
 }
 
 usage() {
-    die 'Usage: subs [-m no-video] [-g gen-links] [-u update-cache] [-d daemonize]'
+    die 'Usage: subs [-m no-video] [-g gen-links] [-u update-cache] [-d daemonize] [-n dont-play]'
 }
 
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
@@ -40,6 +54,7 @@ gen_links() {
 
     count=0
     total=$(sed -e '/^$/d' -e '/^#/d' <"$SUBS_FILE" | wc -l)
+    total=${total##* }
 
     while read -r line ; do
 
@@ -55,20 +70,31 @@ gen_links() {
         case $line in
             UC*)
                 # YT channel IDs always begin with 'UC' and are 24 chars long
-                printf "[%s/%s] using channel ID '%s' for xml link\n" "$count" "$total" "$line"
+                if [ ${#line} -eq 24 ] ; then
+                    printf "[%s/%s] using channel ID '%s' for xml link\n" "$count" "$total" "$line"
 
-                [ ${#line} -eq 24 ] &&
                     printf 'https://youtube.com/feeds/videos.xml?%s\n' \
                         "channel_id=$line" >>"$SUBS_LINKS"
+                else
+                    >&2 printf 'Error: cannot determine channel for %s\n' "$line"
+                fi
                 ;;
             *)
                 # otherwise we are given a username, we must find out its channel ID
-                printf "fetching channel ID for %s...\n" "$line"
+                printf "Fetching channel ID for %s..." "$line"
 
-                curl -sfL --retry 10 "https://youtube.com/user/$line/about" | \
+                data=$(curl -sL --retry 10 "https://youtube.com/user/$line/about")
+                if printf '%s\n' "$data" | grep '404 Not Found' >/dev/null ; then
+                    >&2 printf '\n[ERROR]: Could not determine channel for %s... 404\n' "$line"
+                    >&2 printf '[%s] %s\n' "$(date)" "$line" >> "$SUBS"/ERRORS.log
+                    return 1
+                fi
+
+                printf '%s\n' "$data" | \
                 while read -r line ; do
                     case $line in
                         *channel/UC??????????????????????*)
+                            printf ' Found!\n'
                             line=${line##*channel/}
                             line=${line%%\"*}
                             printf "[%s/%s] using channel ID '%s' for xml link\n" "$count" "$total" "$line"
@@ -76,18 +102,10 @@ gen_links() {
                                 "$line" >>"$SUBS_LINKS"
                             break
                     esac
-                done &
-                sleep "${SUBS_SLEEP_VALUE:-0}"
+                done
         esac
 
     done <"$SUBS_FILE"
-
-    count=0
-    while [ "$count" -ne "$total" ] ; do
-        count=$(wc -l < "$SUBS_LINKS")
-        printf "[%s/%s] waiting for jobs tocomplete...\n"  "$count" "$total"
-        sleep 0.5
-    done
 }
 
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
@@ -97,7 +115,13 @@ gen_links() {
 # with a line of its videos dates, titles, and urls.
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 get_vids() {
-    data=$(curl -sfL --retry 15 "$1")
+    data=$(curl -sL --retry 15 "$1")
+
+    if printf '%s\n' "$data" | grep '404 Not Found' >/dev/null ; then
+        >&2 printf '[ERROR]: Could not get vids for %s... 404\n' "$1"
+        >&2 printf '[%s] %s\n' "$(date)" "$1" >> "$SUBS"/ERRORS.log
+        return 1
+    fi
 
     # hide the first <published> tag which is the channel
     # creation date
@@ -134,6 +158,7 @@ get_vids() {
 
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 # Updates the local cache of subscriptions. ([-u] flag)
+# shellcheck disable=2086
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 update_subs() {
     [ -f "$SUBS_LINKS" ] || die 'Subs links have not been generated.'
@@ -142,6 +167,7 @@ update_subs() {
     mkdir -p "$SUBS_CACHE"
 
     total=$(wc -l <"$SUBS_LINKS")
+    total=${total##* }
 
     count=0
     while read -r link ; do
@@ -152,10 +178,13 @@ update_subs() {
     done <"$SUBS_LINKS"
 
     count=0
-    while [ "$count" -ne "$total" ] ; do
+    max_retries=$total
+    while [ "$count" -ne "$total" ] && [ "$max_retries" -ne "$total" ] ; do
         count=$(printf '%s\n' "$SUBS_CACHE"/* | wc -l)
+        count=${count##* }
         printf "[%s/%s] waiting for fetch jobs to complete...\n"  "$count" "$total"
-        sleep 0.5
+        sleep 1
+        max_retries=$(( max_retries + 1 ))
     done
 
     printf '%s\n\n' 'done!'
@@ -182,26 +211,34 @@ cat_subs() {
 # Finally, play the result with mpv.
 get_sel() {
     if [ -d "$SUBS_CACHE" ] ; then
-        sel=$(cat_subs | $SUBS_MENU_PROG)
+        # Pipe your subs feed into your desired menu and replace HTML escape codes (&quot; -> ")
+        sel=$(cat_subs | sed -e 's/&quot;/"/g' -e 's/&amp;/\&/g' -e 's/&lt;/</g' -e 's/&gt;/>/g' | $SUBS_MENU_PROG)
     else
         die 'Subs cache has not been retrieved.'
     fi
 
     [ "$sel" ] || die Interrupted
 
-    chan="${sel#* }"
-    chan="${chan%%] *}"
-    title=${sel#*"$chan"\] }
+    oldchan="${sel#* }"
+    chan=$(printf '%s' "${oldchan%%] *}" | sed -e 's/\&/&amp;/g' -e 's/"/\&quot;/g'  -e 's/</\&lt;/g' -e 's/>/\&gt;/g' )
+    title=$(printf '%s' "${sel#*"${oldchan%%] *}"\] }" | sed -e 's/\&/&amp;/g' -e 's/"/\&quot;/g'  -e 's/</\&lt;/g' -e 's/>/\&gt;/g' )
     while read -r line ; do
         case $line in
             *"$SEP$title$SEP"*)
                 url=${line##*$SEP}
                 if [ "$url" ] ; then
-                    printf 'playing: %s\n' "$url"
-                    if [ "$(pidof mpv)" ] ; then
-                        echo '{"command": ["loadfile", "'$url'", "append-play"]}' | socat - /tmp/mpvsocket
+                    if [ "$DONT_PLAY" ] ; then
+                        # just print the url
+                        # (useful for piping to other programs)
+                        printf '%s\n' "$url"
                     else
-                        exec mpv $MPV_OPTS --input-ipc-server=/tmp/mpvsocket "$url"
+                        printf 'playing: %s\n' "$url"
+                        if [ "$(pidof mpv)" ] ; then
+                            echo '{"command": ["loadfile", "'$url'", "append-play"]}' | socat - /tmp/mpvsocket
+                        else
+                            # shellcheck disable=2086
+                            exec mpv $MPV_OPTS --input-ipc-server=/tmp/mpvsocket "$url"
+                        fi
                     fi
                 fi
                 break
@@ -215,6 +252,7 @@ daemonize() {
     daemon_file=${XDG_CACHE_HOME:-~/.cache}/subs_daemon.cache
     if [ ! -f "$daemon_file" ] ; then
         cp -f "${SUBS_FILE:=~/files/subs.txt}" "$daemon_file"
+        gen_links
     fi
 
     while true ; do
@@ -223,29 +261,42 @@ daemonize() {
             cp -f "${SUBS_FILE:=~/files/subs.txt}" "$daemon_file"
         fi
         update_subs
-        interval=${SUBS_DAEMON_INTERVAL:-$(( 5 * 60 ))}
-        printf 'Sleeping for %s seconds...\n' "$interval"
-        sleep "$interval"
+        printf 'Sleeping for %s seconds...\n' "$SUBS_DAEMON_INTERVAL"
+        sleep "$SUBS_DAEMON_INTERVAL"
     done
 }
 
 main() {
     mkdir -p "$SUBS"
 
-    case ${1#-} in
-        m)
-            export MPV_OPTS="$MPV_OPTS --no-video"
-            shift
-    esac
-
-    case ${1#-} in
-        h) usage ;;
-        g) gen_links ;;
-        u) update_subs ;;
-        c) cat_subs ;;
-        d) daemonize ;;
-        *) get_sel
-    esac
+    if [ "$1" ] ; then
+        case ${1#-} in
+            g)
+                gen_links
+                ;;
+            u)
+                update_subs
+                ;;
+            c)
+                cat_subs
+                ;;
+            d)
+                daemonize
+                ;;
+            m)
+                MPV_OPTS="$MPV_OPTS --no-video" \
+                get_sel
+                ;;
+            n)
+                DONT_PLAY=true \
+                get_sel
+                ;;
+            *)
+                usage
+        esac
+    else
+        get_sel
+    fi
 }
 
-main "$@" 
+main "$@"
